### ISSUE TITLE
Points are not appearing on Kapta after exporting the WAchat 

### ISSUE THREAD

**Issue by fmousss** [UCL/kapta-mobile#39]
![error Kapta](https://github.com/user-attachments/assets/b47db837-55d4-4a75-9916-59a10497d135)

**Comment by acholyn** [comment]
The url has `share-target` at the end, did you try sharing as an image/data and then it disappeared or is this due to the direct export from whatsapp?

**Comment by acholyn** [comment]
if it's directly from whatsapp could you export it to the slack chat so I can compare the structure?

**Comment by fmousss** [comment]
I sent you the WA group export file on slack.

**Comment by acholyn** [comment]
seems like it was a date-time format issue with the parsing. I believe I've fixed it and I now get a result like this:
<img width="659" alt="image" src="https://github.com/user-attachments/assets/c5f61ca6-9fc2-4dd1-b005-6111ec525b2f">

Let me know if that looks wildly unexpected

**Comment by fmousss** [comment]
Still doesn't work for me ... 
![WhatsApp Image 2024-08-20 at 15 59 27_26e5afde](https://github.com/user-attachments/assets/6c653e63-fef7-4665-b95c-449910795bb5)
